#pragma once

#include <stdint.h>

// WAS 
// #define JOYX_THRESHOLD_LEFT_DOOM 600
// #define JOYX_THRESHOLD_RIGHT_DOOM 400
// #define JOYY_THRESHOLD_UP_DOOM 400
// #define JOYY_THRESHOLD_DOWN_DOOM 600

// #define JOYX_THRESHOLD_LEFT_MENU 650
// #define JOYX_THRESHOLD_RIGHT_MENU 300
// #define JOYY_THRESHOLD_UP_MENU 300
// #define JOYY_THRESHOLD_DOWN_MENU 650

// NEW VALUES
#define JOYX_THRESHOLD_LEFT_DOOM 850
#define JOYX_THRESHOLD_RIGHT_DOOM 600
#define JOYY_THRESHOLD_UP_DOOM 350
#define JOYY_THRESHOLD_DOWN_DOOM 650

// middle ~ 747 JOYX | middle ~ 482 JOYY
#define JOYX_THRESHOLD_LEFT_MENU 850
#define JOYX_THRESHOLD_RIGHT_MENU 600
#define JOYY_THRESHOLD_UP_MENU 350
#define JOYY_THRESHOLD_DOWN_MENU 650

int analogReadHAL(uint32_t channel);